/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package miniproject;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author dell
 */
public class tblpsnmsk extends javax.swing.JFrame {
    koneksi k=new koneksi();
private void tablepsmsk(){
    DefaultTableModel m=new DefaultTableModel();
    m.addColumn("No.Transaksi");
    m.addColumn("Kode Produk");
    m.addColumn("Jumlah");
    m.addColumn("Tanggal Ambil");
    m.addColumn("Keterangan");
    try {
        int no=1;
        String sql="select no_transaksi,kode_barang,jumlah,"
                + "tanggal_ambil,keterangan from detail_transaksi where keterangan='Pesanan masuk' order by no_transaksi asc";
        Connection con=k.getCon();
        PreparedStatement p=con.prepareStatement(sql);
        ResultSet rs=p.executeQuery();
        while (rs.next()) {            
            m.addRow(new Object[]{
            rs.getString(1),
            rs.getString(2),
            rs.getString(3),
            rs.getString(4),
            rs.getString(5)});
        }
        jTable1.setModel(m);
    } catch (SQLException ex){
        System.out.println("tampiltable GAGAL!!!!");
    }
}
private void jumlah(){
    int jumlahbarisi=jTable1.getRowCount();
    int jumlahpesmsk=0;
    int jmlhpsanan;
    for (int i = 0; i < jumlahbarisi; i++) {
        jmlhpsanan=Integer.parseInt(jTable1.getValueAt(i, 2).toString());
        jumlahpesmsk=jumlahpesmsk+jmlhpsanan;
        //jTextField1.setText(String.valueOf(jumlahpesmsk));
        setergeter.setTotalpesmasuk(jumlahpesmsk);
    }
    //jTextField1.setText(String.valueOf(setergeter.getTotalpesmasuk()));
}
    /**
     * Creates new form tblpsnmsk
     */
    public tblpsnmsk() {
        initComponents();
        k.Connect();
        tablepsmsk();
        jumlah();
        //ambilRow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sedang diproses", "Pesanan selesai" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
    int i=jTable1.getSelectedRow();
    TableModel m=jTable1.getModel();
    String notrans=m.getValueAt(i, 0).toString();
    String kodeproduk=m.getValueAt(i, 1).toString();
    String jml=m.getValueAt(i, 2).toString();
    String tgl=m.getValueAt(i, 3).toString();
    //String tgl=m.getValueAt(i, 4).toString();
        try {
            String sql="update detail_transaksi set keterangan='"+jComboBox1.getSelectedItem()
                    +"' where no_transaksi='"+notrans+"' and kode_barang='"+kodeproduk+"' and jumlah='"
                    +jml+"' and tanggal_ambil='"+tgl+"'";
            Connection c=k.getCon();
            PreparedStatement p=c.prepareStatement(sql);
            p.executeUpdate();
            JOptionPane.showMessageDialog(null, "Berahsil mengubah keterangan");
            tablepsmsk();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tblpsnmsk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tblpsnmsk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tblpsnmsk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tblpsnmsk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tblpsnmsk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
