/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package miniproject;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author dell
 */
public class ubahtransaksi extends javax.swing.JFrame {
    koneksi k=new koneksi();
    public static String ubahpesan;
    private DefaultTableModel tabel;
    public static String getUbahpesan() {
        return ubahpesan;
    }

    public static void setUbahpesan(String ubahpesan) {
        ubahtransaksi.ubahpesan = ubahpesan;
    }
    public void tampilcombo (){
        try {
            String sql="Select * From barang";
            Connection kon=k.getCon();
            PreparedStatement pst=kon.prepareStatement(sql);
            ResultSet rs=pst.executeQuery();
            while (rs.next()) {                
                combokode.addItem(rs.getString("kode_barang"));
            }
            rs.last();
            int jumlahdata=rs.getRow();
            rs.first();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    public void loadData(){
        String getDate = "yyyy-MM-dd";
        SimpleDateFormat fm = new SimpleDateFormat(getDate);
        String tanggal = String.valueOf(fm.format(dtanggal.getDate()));
        tabel= (DefaultTableModel) tableTransaksi.getModel();
        tabel.addRow(new Object[]{
        noPes.getText(),
        combokode.getSelectedItem(),
        tharga.getText(),
        tjumlah.getText(),
        ttotal.getText(),
        tanggal});
    }
private void tampiltable(){
    DefaultTableModel model=new DefaultTableModel();
        model.addColumn(("No. Pemesanan"));
        model.addColumn(("Tanggal Transaksi"));
        model.addColumn(("Total Item"));
        model.addColumn(("Total Harga"));
        model.addColumn("Bayar Awal");
        model.addColumn("Kurang");
        model.addColumn("Kode Diskon");
        model.addColumn("Id Karyawan");
        
        try {
            int no=1;
            PreparedStatement pst=k.getCon().prepareStatement("Select no_transaksi,tgl_transaksi, "
                    + "total_item, bayar_awal, kurang, total_pembayaran, kode_diskon, id_karywan From "
                    + "transaksi");
            ResultSet rst=pst.executeQuery();
            
            while (rst.next()) {                
                model.addRow(new Object[] {
                    rst.getString(1),
                    rst.getString(2),
                    rst.getString(3),
                    rst.getString(4),
                    rst.getString(5),
                    rst.getString(6),
                    rst.getString(7),
                    rst.getString(8)});
                
                tableTransaksi.setModel(model);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
}
    /**
     * Creates new form ubahtransaksi
     */
    public ubahtransaksi() {
        initComponents();
        k.Connect();
        tampiltable();
        tampilcombo();
        
        Date date=new Date();
        SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
        ttanggal.setText(s.format(date));
        ttanggal.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableTransaksi = new javax.swing.JTable();
        bubah = new javax.swing.JButton();
        noPes = new javax.swing.JTextField();
        tjumlah = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ttotal = new javax.swing.JTextField();
        dtanggal = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        tharga = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bbayar = new javax.swing.JButton();
        bhapus = new javax.swing.JButton();
        combokode = new javax.swing.JComboBox<>();
        btambah = new javax.swing.JButton();
        ttanggal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableTransaksiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableTransaksi);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 87, -1, 370));

        bubah.setText("ubah");
        bubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bubahActionPerformed(evt);
            }
        });
        getContentPane().add(bubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, -1, -1));

        noPes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noPesActionPerformed(evt);
            }
        });
        getContentPane().add(noPes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 130, 30));

        tjumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tjumlahActionPerformed(evt);
            }
        });
        getContentPane().add(tjumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, 80, 20));

        jLabel1.setText("jumlah");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, 50, 20));

        jLabel2.setText("total harga");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, -1, -1));

        ttotal.setText(" \n");
        ttotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ttotalActionPerformed(evt);
            }
        });
        getContentPane().add(ttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, 80, 20));

        dtanggal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dtanggalMouseClicked(evt);
            }
        });
        getContentPane().add(dtanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, -1, -1));

        jLabel3.setText("Tanggal Pengambilan");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, 70, 20));
        getContentPane().add(tharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, 80, 20));

        jLabel4.setText("Harga");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 104, -1, 20));

        jLabel5.setText("kode_produk");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, -1, -1));

        bbayar.setText("bayar");
        bbayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbayarActionPerformed(evt);
            }
        });
        getContentPane().add(bbayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, -1, -1));

        bhapus.setText("hapus");
        bhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhapusActionPerformed(evt);
            }
        });
        getContentPane().add(bhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, -1, -1));

        combokode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                combokodeMouseClicked(evt);
            }
        });
        combokode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combokodeActionPerformed(evt);
            }
        });
        getContentPane().add(combokode, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, 80, 20));

        btambah.setText("tambah");
        btambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btambahActionPerformed(evt);
            }
        });
        getContentPane().add(btambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 230, -1, -1));
        getContentPane().add(ttanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 140, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void noPesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noPesActionPerformed
        DefaultTableModel mdl=new DefaultTableModel();
        mdl.addColumn(("No. Pemesanan"));
        mdl.addColumn(("Kode Produk"));
        mdl.addColumn("Harga Satuan");
        mdl.addColumn(("Jumlah"));
        mdl.addColumn(("Total Harga"));
        mdl.addColumn("Tanggal Pengambilan");
        
        try {
            int no=1;
            String sql="select * from detail_transaksi where no_transaksi= '"+noPes.getText()+"'";
            Connection c=k.getCon();
            PreparedStatement p=c.prepareStatement(sql);
            ResultSet rs=p.executeQuery();
            while (rs.next()) {                
                mdl.addRow(new Object[] {
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4),
                    rs.getString(5),
                    rs.getString(6)});
                
                tableTransaksi.setModel(mdl);
                
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_noPesActionPerformed

    private void tableTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableTransaksiMouseClicked
        int i = tableTransaksi.getSelectedRow();
        TableModel model = tableTransaksi.getModel();
        String nopes=model.getValueAt(i, 0).toString();
        String harga=model.getValueAt(i, 2).toString();
        String jumlah=model.getValueAt(i, 3).toString();
        noPes.setText(nopes);
        tharga.setText(harga);
        tjumlah.setText(jumlah);
    }//GEN-LAST:event_tableTransaksiMouseClicked

    private void ttotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ttotalActionPerformed
       
    }//GEN-LAST:event_ttotalActionPerformed

    private void tjumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tjumlahActionPerformed
        int jumlah,harga,total;
        jumlah=Integer.valueOf(tjumlah.getText());
        harga=Integer.valueOf(tharga.getText());
        total=jumlah*harga;
        ttotal.setText(String.valueOf(total));
    }//GEN-LAST:event_tjumlahActionPerformed

    private void bubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bubahActionPerformed
        TableModel model=tableTransaksi.getModel();
        int i=tableTransaksi.getSelectedRow();
        String getDate = "yyyy-MM-dd";
        SimpleDateFormat fm = new SimpleDateFormat(getDate);
        String tanggal = String.valueOf(fm.format(dtanggal.getDate()));
        String produk=model.getValueAt(i, 1).toString();
        String tgl=model.getValueAt(i, 5).toString();
        try {
            String sql="update detail_transaksi set jumlah= '"+tjumlah.getText()
                    +"', total_harga= '"+ttotal.getText()+"', tanggal_ambil= '"
                    +tanggal+"' where no_transaksi= '"+noPes.getText()+"' and kode_barang= '"
                    +produk+"' and tanggal_ambil= '"+tgl+"'";
            Connection c=k.getCon();
            PreparedStatement p=c.prepareStatement(sql);
            p.executeUpdate();
            JOptionPane.showMessageDialog(null, "Berhasil mengubah pesanan");
            noPesActionPerformed(evt);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        tharga.setText("");
        tjumlah.setText("");
        ttotal.setText("");
        dtanggal.setDate(null);
    }//GEN-LAST:event_bubahActionPerformed

    private void dtanggalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dtanggalMouseClicked
        
    }//GEN-LAST:event_dtanggalMouseClicked

    private void bbayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbayarActionPerformed
        setergeter.setUbahpes(noPes.getText().toString());
        JOptionPane.showMessageDialog(null, "Pesanan berhasil diperbarui!!!!");
        this.dispose();
        new ubahpes().setVisible(true);
    }//GEN-LAST:event_bbayarActionPerformed

    private void bhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhapusActionPerformed
        /*int i = tableTransaksi.getSelectedRow();
        TableModel model = tableTransaksi.getModel();
        String nop=model.getValueAt(i, 0).toString();*/
        try {
            DefaultTableModel model=new DefaultTableModel();
        model.addColumn(("No. Pemesanan"));
        model.addColumn(("Tanggal Transaksi"));
        model.addColumn(("Total Item"));
        model.addColumn(("Total Harga"));
        model.addColumn("Bayar Awal");
        model.addColumn("Kurang");
        model.addColumn("Kode Diskon");
        model.addColumn("Id Karyawan");
            String sql="delete from transaksi where no_transaksi= '"+noPes.getText()+"'";
            Connection c=k.getCon();
            PreparedStatement p=c.prepareStatement(sql);
            p.execute();
            JOptionPane.showMessageDialog(null, "transaksi berhasil dihapus!!!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        try {
            String sql="delete from detail_transaksi where no_transaksi= '"+noPes.getText()+"'";
            Connection c=k.getCon();
            PreparedStatement p=c.prepareStatement(sql);
            p.execute();
            JOptionPane.showMessageDialog(null, "transaksi berhasil dihapus");
            tampiltable();
        } catch (Exception e) {
        }
        tampiltable();
    }//GEN-LAST:event_bhapusActionPerformed

    private void combokodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combokodeActionPerformed
        try {
        String sql = "SELECT * FROM barang where kode_barang='"+combokode.getSelectedItem()+"'";
        java.sql.Connection con = k.getCon();
        java.sql.PreparedStatement pst = con.prepareStatement(sql);
        java.sql.ResultSet rst = pst.executeQuery();
        while(rst.next()){
            tharga.setText(rst.getString("harga_barang"));
            tjumlah.setText("");
            ttotal.setText("");
        }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_combokodeActionPerformed

    private void btambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btambahActionPerformed
        //tambahTransaksi();
        String getDate = "yyyy-MM-dd";
        SimpleDateFormat fm = new SimpleDateFormat(getDate);
        String tanggal = String.valueOf(fm.format(dtanggal.getDate()));
        try {
            String sql="insert into detail_transaksi values ('"+noPes.getText()+"','"
                    +combokode.getSelectedItem()+"','"+tharga.getText()+"','"+tjumlah.getText()+"','"
                    +ttotal.getText()+"','"+tanggal+"')";
            Connection c=k.getCon();
            PreparedStatement p=c.prepareStatement(sql);
            p.execute();
            p.close();
            //JOptionPane.showMessageDialog(null, "Berhasil menambahkan barang");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        loadData();
    }//GEN-LAST:event_btambahActionPerformed

    private void combokodeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_combokodeMouseClicked
        
    }//GEN-LAST:event_combokodeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ubahtransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ubahtransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ubahtransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ubahtransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ubahtransaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bbayar;
    private javax.swing.JButton bhapus;
    private javax.swing.JButton btambah;
    private javax.swing.JButton bubah;
    private javax.swing.JComboBox<String> combokode;
    private com.toedter.calendar.JDateChooser dtanggal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField noPes;
    private javax.swing.JTable tableTransaksi;
    private javax.swing.JTextField tharga;
    private javax.swing.JTextField tjumlah;
    private javax.swing.JTextField ttanggal;
    private javax.swing.JTextField ttotal;
    // End of variables declaration//GEN-END:variables
}
